# The generic alembic environment.

[sqlalchemy]
# use flask db url environment variable to provide SQLAlchemy url
# example SQLALCHEMY_DATABASE_URL=postgresql://user:password@localhost/dbname
sqlalchemy.url = driver://user:password@localhost/dbname


[loggers]
keys=root,sqlalchemy.engine,sqlalchemy.pool,alembic

[handlers]
keys=console

[formatters]
keys=generic

[logger_root]
level=WARN
handlers=console
qualname=

[logger_sqlalchemy.engine]
level=WARN
handlers=
qualname=sqlalchemy.engine

[logger_sqlalchemy.pool]
level=WARN
handlers=
qualname=sqlalchemy.pool

[logger_alembic]
level=INFO
handlers=
qualname=alembic

[handler_console]
class=StreamHandler
level=NOTSET
formatter=generic
args=(sys.stderr,)

[formatter_generic]
format=%(levelname)-5.5s [%(name)s] %(message)s
datefmt=%H:%M:%S
